import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satoshiFont = localFont({
  src: './fonts/Satoshi.woff2',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={satoshiFont.className}>
      <body
        className="bg-primary-100 text-black"
      >
        {children}
      </body>
    </html>
  );
}
